### PR TITLE
Changed to token endpoint to https

### PR DESCRIPTION
**Pull request by tiede**

### CODE REVIEW

**Comment by jfrmilner** [comment]
I can guess from the subject the issue you've spotted but I'm not able to see the code changes as its classified the file as BIN and not text. I'll have to look into why that is.

**Comment by tiede** [comment]
Yeah - I had the same problem when doing a diff on the file from your repo and my changes. Seems to have something to do with the file encoding being UTF16 LE.

**Comment by jfrmilner** [comment]
Changed to token endpoint to https

**Comment by jfrmilner** [comment]
Agreed. Yesterday I updated the gitattributes for ps1 files so hopefully that'll sort things out. Thank you for the fix.

**Pull request merged**
